In [14]:
import yfinance as yf

In [18]:
stock = yf.Ticker("VALE3.SA")
stock

yfinance.Ticker object <VALE3.SA>

# Stock Actions

In [20]:
stock.actions

                           Dividends  Stock Splits
Date
2004-08-19 00:00:00-03:00   0.000000           3.0
2006-05-22 00:00:00-03:00   0.000000           2.0
2007-09-03 00:00:00-03:00   0.000000           2.0
2008-04-11 00:00:00-03:00   0.436585           0.0
2008-10-17 00:00:00-03:00   0.138520           0.0
2009-04-16 00:00:00-03:00   0.524586           0.0
2009-10-16 00:00:00-03:00   0.492036           0.0
2010-04-15 00:00:00-03:00   0.421661           0.0
2010-10-15 00:00:00-03:00   0.471881           0.0
2011-01-17 00:00:00-02:00   0.320048           0.0
2011-04-14 00:00:00-03:00   0.608247           0.0
2011-08-12 00:00:00-03:00   0.933403           0.0
2011-10-17 00:00:00-02:00   0.634329           0.0
2012-04-16 00:00:00-03:00   1.075280           0.0
2012-10-17 00:00:00-03:00   1.186520           0.0
2013-04-17 00:00:00-03:00   0.864045           0.0
2013-10-18 00:00:00-03:00   0.120605           0.0
2014-04-15 00:00:00-03:00   0.898904           0.0
2014-10-17 00:00:00-03:00   0.990870           0.0
2015-04-15 00:00:00-03:00   0.601761           0.0
2015-10-16 00:00:00-03:00   0.373610           0.0
2016-12-02 00:00:00-02:00   0.166294           0.0
2017-04-24 00:00:00-03:00   0.905572           0.0
2017-12-22 00:00:00-02:00   0.419912           0.0
2018-03-07 00:00:00-03:00   0.488511           0.0
2018-08-03 00:00:00-03:00   1.480362           0.0
2019-12-27 00:00:00-03:00   1.414364           0.0
2020-09-22 00:00:00-03:00   2.407510           0.0
2021-03-05 00:00:00-03:00   4.261646           0.0
2021-06-24 00:00:00-03:00   2.189670           0.0
2021-09-23 00:00:00-03:00   8.197239           0.0
2022-03-09 00:00:00-03:00   3.719256           0.0
2022-08-12 00:00:00-03:00   3.572057           0.0
2022-12-13 00:00:00-03:00   0.292013           0.0
2023-03-14 00:00:00-03:00   1.827646           0.0
2023-08-14 00:00:00-03:00   1.918472           0.0
2023-11-22 00:00:00-03:00   0.765771           0.0
2024-03-12 00:00:00-03:00   2.738548           0.0

In [21]:
stock.dividends

Date
2008-04-11 00:00:00-03:00    0.436585
2008-10-17 00:00:00-03:00    0.138520
2009-04-16 00:00:00-03:00    0.524586
2009-10-16 00:00:00-03:00    0.492036
2010-04-15 00:00:00-03:00    0.421661
2010-10-15 00:00:00-03:00    0.471881
2011-01-17 00:00:00-02:00    0.320048
2011-04-14 00:00:00-03:00    0.608247
2011-08-12 00:00:00-03:00    0.933403
2011-10-17 00:00:00-02:00    0.634329
2012-04-16 00:00:00-03:00    1.075280
2012-10-17 00:00:00-03:00    1.186520
2013-04-17 00:00:00-03:00    0.864045
2013-10-18 00:00:00-03:00    0.120605
2014-04-15 00:00:00-03:00    0.898904
2014-10-17 00:00:00-03:00    0.990870
2015-04-15 00:00:00-03:00    0.601761
2015-10-16 00:00:00-03:00    0.373610
2016-12-02 00:00:00-02:00    0.166294
2017-04-24 00:00:00-03:00    0.905572
2017-12-22 00:00:00-02:00    0.419912
2018-03-07 00:00:00-03:00    0.488511
2018-08-03 00:00:00-03:00    1.480362
2019-12-27 00:00:00-03:00    1.414364
2020-09-22 00:00:00-03:00    2.407510
2021-03-05 00:00:00-03:00    4.261646
2021-06-24 00:00:00-03:00    2.189670
2021-09-23 00:00:00-03:00    8.197239
2022-03-09 00:00:00-03:00    3.719256
2022-08-12 00:00:00-03:00    3.572057
2022-12-13 00:00:00-03:00    0.292013
2023-03-14 00:00:00-03:00    1.827646
2023-08-14 00:00:00-03:00    1.918472
2023-11-22 00:00:00-03:00    0.765771
2024-03-12 00:00:00-03:00    2.738548
Name: Dividends, dtype: float64

In [22]:
stock.splits

Date
2004-08-19 00:00:00-03:00    3.0
2006-05-22 00:00:00-03:00    2.0
2007-09-03 00:00:00-03:00    2.0
Name: Stock Splits, dtype: float64

In [23]:
stock.capital_gains

[]

# Share count

In [24]:
stock.get_shares_full()

2022-12-08 00:00:00-03:00    4664059904
2022-12-30 00:00:00-03:00    4717590016
2023-01-01 00:00:00-03:00    4664059904
2023-01-04 00:00:00-03:00    4674520064
2023-01-06 00:00:00-03:00    4672779776
                                ...
2024-05-25 00:00:00-03:00    4280329984
2024-05-29 00:00:00-03:00    4374790144
2024-05-29 00:00:00-03:00    4275689984
2024-06-05 00:00:00-03:00    4319680000
2024-06-05 00:00:00-03:00    4275689984
Length: 147, dtype: int64

# Dados financeiros

## Demonstração de resultados

In [25]:
stock.income_stmt

,2023-12-31,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Tax Effect Of Unusual Items,-568659000.0,247821141.499419,240407027.521072,-882841201.716738,NaN
Tax Rate For Calcs,0.273,0.150195,0.158999,0.10515,NaN
Normalized EBITDA,17643000000.0,22247000000.0,32616000000.0,20958000000.0,NaN
Total Unusual Items,-2083000000.0,1650000000.0,1512000000.0,-8396000000.0,NaN
Total Unusual Items Excluding Goodwill,-2083000000.0,1650000000.0,1512000000.0,-8396000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,7983000000.0,16728000000.0,24821000000.0,6605000000.0,NaN
Reconciled Depreciation,3070000000.0,3171000000.0,3034000000.0,3215000000.0,NaN
Reconciled Cost Of Revenue,21066000000.0,20898000000.0,18737000000.0,14398000000.0,NaN
EBITDA,15560000000.0,23897000000.0,34128000000.0,12562000000.0,NaN
EBIT,12490000000.0,20726000000.0,31094000000.0,9347000000.0,NaN
Net Interest Income,-1515000000.0,41000000.0,-1542000000.0,-3183000000.0,NaN
Interest Expense,1339000000.0,945000000.0,1553000000.0,2357000000.0,NaN
Interest Income,NaN,659000000.0,NaN,NaN,247000000.0
Normalized Income,9497341000.0,15325821141.499418,23549407027.521072,14118158798.283262,NaN
Net Income From Continuing And Discontinued Operation,7983000000.0,18788000000.0,22445000000.0,4881000000.0,NaN
Total Expenses,25927000000.0,26054000000.0,23660000000.0,19956000000.0,NaN
Total Operating Income As Reported,14205000000.0,17208000000.0,27693000000.0,12823000000.0,NaN
Diluted Average Shares,4369961000.0,4642432000.0,5016848000.0,5129585000.0,NaN
Basic Average Shares,4366130000.0,4637794000.0,5012424000.0,5129585000.0,NaN
Diluted EPS,1.83,4.05,4.47,0.95,NaN
Basic EPS,1.83,4.05,4.47,0.95,NaN
Diluted NI Availto Com Stockholders,7983000000.0,18788000000.0,22445000000.0,4881000000.0,NaN
Net Income Common Stockholders,7983000000.0,18788000000.0,22445000000.0,4881000000.0,NaN
Net Income,7983000000.0,18788000000.0,22445000000.0,4881000000.0,NaN
Minority Interests,-122000000.0,-82000000.0,-23000000.0,350000000.0,NaN
Net Income Including Noncontrolling Interests,8105000000.0,18870000000.0,22468000000.0,4531000000.0,NaN
Net Income Discontinuous Operations,0.0,2060000000.0,-2376000000.0,-1724000000.0,NaN
Net Income Continuous Operations,8105000000.0,16810000000.0,24844000000.0,6255000000.0,NaN
Tax Provision,3046000000.0,2971000000.0,4697000000.0,735000000.0,NaN
Pretax Income,11151000000.0,19781000000.0,29541000000.0,6990000000.0,NaN
Other Income Expense,-3191000000.0,1955000000.0,241000000.0,-9416000000.0,NaN
Other Non Operating Income Expenses,NaN,NaN,NaN,-115000000.0,-89000000.0
Special Income Charges,-1652000000.0,-577000000.0,-3149000000.0,-6766000000.0,NaN
Gain On Sale Of Ppe,-74000000.0,-46000000.0,-5000000.0,-19000000.0,NaN
Other Special Charges,1312000000.0,1304000000.0,2718000000.0,5439000000.0,NaN
Impairment Of Capital Assets,266000000.0,-773000000.0,426000000.0,1308000000.0,NaN
Earnings From Equity Interest,-1108000000.0,305000000.0,-1271000000.0,-1020000000.0,NaN
Gain On Sale Of Security,-431000000.0,2227000000.0,4661000000.0,-1630000000.0,NaN
Net Non Operating Interest Income Expense,-1515000000.0,41000000.0,-1542000000.0,-3183000000.0,NaN
Total Other Finance Cost,176000000.0,-327000000.0,-11000000.0,826000000.0,NaN
Interest Expense Non Operating,1339000000.0,945000000.0,1553000000.0,2357000000.0,NaN
Interest Income Non Operating,NaN,659000000.0,NaN,NaN,247000000.0
Operating Income,15857000000.0,17785000000.0,30842000000.0,19589000000.0,NaN
Operating Expense,1838000000.0,2026000000.0,1931000000.0,2392000000.0,NaN
Other Operating Expenses,562000000.0,851000000.0,901000000.0,1486000000.0,NaN
Depreciation Amortization Depletion Income Statement,47000000.0,41000000.0,42000000.0,49000000.0,NaN
Depreciation And Amortization In Income Statement,47000000.0,41000000.0,42000000.0,49000000.0,NaN
Research And Development,723000000.0,660000000.0,549000000.0,415000000.0,NaN
Selling General And Administration,506000000.0,474000000.0,439000000.0,442000000.0,NaN
Selling And Marketing Expense,26000000.0,22000000.0,27000000.0,98000000.0,NaN
General And Administrative Expense,480000000.0,452000000.0,412000000.0,344000000.0,NaN
Other Gand A,237000000.0,222000000.0,195000000.0,176000000.0,NaN
Salaries And Wages,243000000.0,230000000.0,217000000.0,168000000.0,NaN
Gross Profit,17695000000.0,19811000000.0,32773000000.0,21981000000.0,NaN
Cost Of Revenue,24089000000.0,24028000000.0,21729000000.0,17564000000.0,NaN
Total Revenue,41784000000.0,43839000000.0,54502000000.0,39545000000.0,NaN
Operating Revenue,41648000000.0,43314000000.0,53891000000.0,38743000000.0,NaN

In [26]:
stock.quarterly_income_stmt

,2024-03-31,2023-12-31,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30
Tax Effect Of Unusual Items,-94006557.377049,-159980641.066328,-22812332.439678,-167960000.0,-62263066.202091,NaN,NaN
Tax Rate For Calcs,0.209836,0.225008,0.04256,0.34,0.182056,NaN,NaN
Normalized EBITDA,3551000000.0,5356000000.0,4539000000.0,4248000000.0,3607000000.0,NaN,NaN
Total Unusual Items,-448000000.0,-711000000.0,-536000000.0,-494000000.0,-342000000.0,NaN,NaN
Total Unusual Items Excluding Goodwill,-448000000.0,-711000000.0,-536000000.0,-494000000.0,-342000000.0,NaN,NaN
Net Income From Continuing Operation Net Minority Interest,1679000000.0,2418000000.0,2836000000.0,892000000.0,1837000000.0,NaN,NaN
Reconciled Depreciation,714000000.0,855000000.0,780000000.0,779000000.0,656000000.0,NaN,NaN
Reconciled Cost Of Revenue,4663000000.0,6046000000.0,5541000000.0,5175000000.0,4304000000.0,NaN,NaN
EBITDA,3103000000.0,4645000000.0,4003000000.0,3754000000.0,3265000000.0,NaN,NaN
EBIT,2389000000.0,3790000000.0,3223000000.0,2975000000.0,2609000000.0,NaN,NaN
Net Interest Income,-147000000.0,-822000000.0,-307000000.0,-52000000.0,-334000000.0,NaN,NaN
Interest Expense,254000000.0,639000000.0,239000000.0,255000000.0,313000000.0,NaN,NaN
Interest Income,164000000.0,NaN,30000000.0,321000000.0,NaN,-99000000.0,470000000.0
Normalized Income,2032993442.622951,2969019358.933672,3349187667.560322,1218040000.0,2116736933.797909,NaN,NaN
Net Income From Continuing And Discontinued Operation,1679000000.0,2418000000.0,2836000000.0,892000000.0,1837000000.0,NaN,NaN
Total Expenses,5853000000.0,7218000000.0,6890000000.0,6412000000.0,5407000000.0,NaN,NaN
Total Operating Income As Reported,2448000000.0,5177000000.0,3275000000.0,2872000000.0,2881000000.0,NaN,NaN
Diluted Average Shares,4289631000.0,4317857143.0,4318388000.0,4737806000.0,4456941000.0,NaN,NaN
Basic Average Shares,4285865000.0,4317857143.0,4314556000.0,4396778000.0,4453110000.0,NaN,NaN
Diluted EPS,0.39,0.56,0.66,0.2,0.41,NaN,NaN
Basic EPS,0.39,0.56,0.66,0.2,0.41,NaN,NaN
Diluted NI Availto Com Stockholders,1679000000.0,2418000000.0,2836000000.0,892000000.0,1837000000.0,NaN,NaN
Net Income Common Stockholders,1679000000.0,2418000000.0,2836000000.0,892000000.0,1837000000.0,NaN,NaN
Net Income,1679000000.0,2418000000.0,2836000000.0,892000000.0,1837000000.0,NaN,NaN
Minority Interests,-8000000.0,-24000000.0,-21000000.0,-36000000.0,-41000000.0,NaN,NaN
Net Income Including Noncontrolling Interests,1687000000.0,2442000000.0,2857000000.0,928000000.0,1878000000.0,NaN,NaN
Net Income Discontinuous Operations,NaN,0.0,0.0,0.0,0.0,0.0,NaN
Net Income Continuous Operations,1687000000.0,2442000000.0,2857000000.0,928000000.0,1878000000.0,NaN,NaN
Tax Provision,448000000.0,709000000.0,127000000.0,1792000000.0,418000000.0,NaN,NaN
Pretax Income,2135000000.0,3151000000.0,2984000000.0,2720000000.0,2296000000.0,NaN,NaN
Other Income Expense,-324000000.0,-1863000000.0,-442000000.0,-489000000.0,-397000000.0,NaN,NaN
Special Income Charges,-158000000.0,-659000000.0,-458000000.0,-389000000.0,-146000000.0,NaN,NaN
Other Special Charges,152000000.0,464000000.0,383000000.0,323000000.0,142000000.0,NaN,NaN
Impairment Of Capital Assets,6000000.0,121000000.0,75000000.0,66000000.0,4000000.0,NaN,NaN
Earnings From Equity Interest,124000000.0,-1152000000.0,94000000.0,5000000.0,-55000000.0,NaN,NaN
Gain On Sale Of Security,-290000000.0,-52000000.0,-78000000.0,-105000000.0,-196000000.0,NaN,NaN
Net Non Operating Interest Income Expense,-147000000.0,-822000000.0,-307000000.0,-52000000.0,-334000000.0,NaN,NaN
Total Other Finance Cost,57000000.0,-121000000.0,98000000.0,118000000.0,21000000.0,NaN,NaN
Interest Expense Non Operating,254000000.0,639000000.0,239000000.0,255000000.0,313000000.0,NaN,NaN
Interest Income Non Operating,164000000.0,NaN,30000000.0,321000000.0,NaN,-99000000.0,470000000.0
Operating Income,2606000000.0,5836000000.0,3733000000.0,3261000000.0,3027000000.0,NaN,NaN
Operating Expense,486000000.0,327000000.0,581000000.0,472000000.0,458000000.0,NaN,NaN
Other Operating Expenses,190000000.0,-50000000.0,243000000.0,168000000.0,201000000.0,NaN,NaN
Depreciation Amortization Depletion Income Statement,10000000.0,10000000.0,12000000.0,14000000.0,11000000.0,NaN,NaN
Depreciation And Amortization In Income Statement,10000000.0,10000000.0,12000000.0,14000000.0,11000000.0,NaN,NaN
Research And Development,156000000.0,231000000.0,188000000.0,165000000.0,139000000.0,NaN,NaN
Selling General And Administration,130000000.0,136000000.0,138000000.0,125000000.0,107000000.0,NaN,NaN
Selling And Marketing Expense,NaN,-39000000.0,26000000.0,21000000.0,18000000.0,49000000.0,NaN
General And Administrative Expense,130000000.0,175000000.0,112000000.0,104000000.0,107000000.0,NaN,NaN
Other Gand A,63000000.0,82000000.0,59000000.0,52000000.0,51000000.0,NaN,NaN
Salaries And Wages,67000000.0,93000000.0,53000000.0,52000000.0,56000000.0,NaN,NaN
Gross Profit,3092000000.0,6163000000.0,4314000000.0,3733000000.0,3485000000.0,NaN,NaN
Cost Of Revenue,5367000000.0,6891000000.0,6309000000.0,5940000000.0,4949000000.0,NaN,NaN
Total Revenue,8459000000.0,13054000000.0,10623000000.0,9673000000.0,8434000000.0,NaN,NaN
Operating Revenue,8459000000.0,13011000000.0,10581000000.0,9647000000.0,8434000000.0,NaN,NaN

## Balanço Patrimonial

In [28]:
stock.balance_sheet

,2023-12-31,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Treasury Shares Number,239153280.0,295810551.0,292841474.0,154563828.0,NaN
Ordinary Shares Number,4299854288.0,4483078700.0,4839616924.0,5129910942.0,NaN
Share Issued,4539007568.0,4778889251.0,5132458398.0,5284474770.0,NaN
Net Debt,11736000000.0,9170000000.0,3878000000.0,6338000000.0,NaN
Total Debt,16797000000.0,15437000000.0,17201000000.0,19825000000.0,NaN
...,...,...,...,...,...
Allowance For Doubtful Accounts Receivable,-44000000.0,-43000000.0,-48000000.0,-50000000.0,NaN
Gross Accounts Receivable,4241000000.0,4362000000.0,3962000000.0,5043000000.0,NaN
Cash Cash Equivalents And Short Term Investments,3660000000.0,4797000000.0,11905000000.0,14258000000.0,NaN
Other Short Term Investments,51000000.0,61000000.0,184000000.0,771000000.0,NaN
Cash And Cash Equivalents,3609000000.0,4736000000.0,11721000000.0,13487000000.0,NaN

In [29]:
stock.quarterly_balance_sheet

,2024-03-31,2023-12-31,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30
Treasury Shares Number,258676398.0,239153280.0,236153280.0,195614711.0,99008077.0,NaN,NaN
Ordinary Shares Number,4280331182.0,4299854288.0,4302854300.0,4343392869.0,4439999491.0,NaN,NaN
Share Issued,4539007580.0,4539007568.0,4539007580.0,4539007580.0,4539007568.0,NaN,NaN
Net Debt,12079000000.0,11736000000.0,10994000000.0,9962000000.0,9605000000.0,NaN,NaN
Total Debt,17295000000.0,16797000000.0,16441000000.0,16465000000.0,15830000000.0,NaN,NaN
...,...,...,...,...,...,...,...
Allowance For Doubtful Accounts Receivable,-44000000.0,-44000000.0,-47000000.0,-44000000.0,-43000000.0,NaN,NaN
Gross Accounts Receivable,2277000000.0,4241000000.0,3395000000.0,3011000000.0,2730000000.0,NaN,NaN
Cash Cash Equivalents And Short Term Investments,3834000000.0,3660000000.0,4027000000.0,5029000000.0,4758000000.0,NaN,NaN
Other Short Term Investments,44000000.0,51000000.0,60000000.0,46000000.0,53000000.0,NaN,NaN
Cash And Cash Equivalents,3790000000.0,3609000000.0,3967000000.0,4983000000.0,4705000000.0,NaN,NaN

## Fluxo de caixa

In [30]:
stock.cash_flow

,2023-12-31,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Free Cash Flow,7245000000.0,6039000000.0,20646000000.0,10095000000.0,NaN
Repurchase Of Capital Stock,-2714000000.0,-6036000000.0,-5546000000.0,0.0,NaN
Repayment Of Debt,-891000000.0,-2524000000.0,-2142000000.0,-6268000000.0,NaN
Issuance Of Debt,1950000000.0,1275000000.0,930000000.0,6800000000.0,NaN
Capital Expenditure,-5920000000.0,-5446000000.0,-5033000000.0,-4227000000.0,NaN
End Cash Position,3609000000.0,4736000000.0,11721000000.0,13487000000.0,NaN
Other Cash Adjustment Outside Changein Cash,-703000000.0,-11000000.0,0.0,-15000000.0,NaN
Beginning Cash Position,4736000000.0,11721000000.0,13487000000.0,7350000000.0,NaN
Effect Of Exchange Rate Changes,69000000.0,138000000.0,-551000000.0,-825000000.0,NaN
Changes In Cash,-493000000.0,-7112000000.0,-1215000000.0,6977000000.0,NaN
Cash Flow From Discontinued Operation,NaN,NaN,NaN,0.0,0.0
Financing Cash Flow,-7339000000.0,-13911000000.0,-20284000000.0,-2676000000.0,NaN
Cash From Discontinued Financing Activities,0.0,-11000000.0,-13000000.0,-15000000.0,NaN
Cash Flow From Continuing Financing Activities,-7339000000.0,-13900000000.0,-20271000000.0,-2661000000.0,NaN
Net Other Financing Charges,-171000000.0,-12000000.0,-30000000.0,157000000.0,NaN
Cash Dividends Paid,-5513000000.0,-6603000000.0,-13483000000.0,-3350000000.0,NaN
Common Stock Dividend Paid,NaN,NaN,NaN,-3350000000.0,0.0
Net Common Stock Issuance,-2714000000.0,-6036000000.0,-5546000000.0,0.0,NaN
Common Stock Payments,-2714000000.0,-6036000000.0,-5546000000.0,0.0,NaN
Net Issuance Payments Of Debt,1059000000.0,-1249000000.0,-1212000000.0,532000000.0,NaN
Net Long Term Debt Issuance,1059000000.0,-1249000000.0,-1212000000.0,532000000.0,NaN
Long Term Debt Payments,-891000000.0,-2524000000.0,-2142000000.0,-6268000000.0,NaN
Long Term Debt Issuance,1950000000.0,1275000000.0,930000000.0,6800000000.0,NaN
Investing Cash Flow,-6319000000.0,-4686000000.0,-6610000000.0,-4669000000.0,NaN
Cash From Discontinued Investing Activities,0.0,-103000000.0,-2469000000.0,-129000000.0,NaN
Cash Flow From Continuing Investing Activities,-6319000000.0,-4583000000.0,-4141000000.0,-4540000000.0,NaN
Net Other Investing Changes,-19000000.0,145000000.0,-129000000.0,-568000000.0,NaN
Dividends Received Cfi,204000000.0,219000000.0,190000000.0,173000000.0,NaN
Net Investment Purchase And Sale,-12000000.0,837000000.0,1286000000.0,213000000.0,NaN
Sale Of Investment,127000000.0,837000000.0,1286000000.0,407000000.0,NaN
Purchase Of Investment,-139000000.0,NaN,-542000000.0,-194000000.0,-828000000.0
Net Business Purchase And Sale,-572000000.0,-338000000.0,-455000000.0,-131000000.0,NaN
Purchase Of Business,-572000000.0,-338000000.0,-455000000.0,-131000000.0,NaN
Capital Expenditure Reported,-5920000000.0,-5446000000.0,-5033000000.0,-4227000000.0,NaN
Operating Cash Flow,13165000000.0,11485000000.0,25679000000.0,14322000000.0,NaN
Cash From Discontinued Operating Activities,0.0,41000000.0,-316000000.0,-1055000000.0,NaN
Cash Flow From Continuing Operating Activities,13165000000.0,11444000000.0,25995000000.0,15377000000.0,NaN
Taxes Refund Paid,-1890000000.0,-4637000000.0,-4385000000.0,-1736000000.0,NaN
Interest Paid Cfo,-976000000.0,-1156000000.0,-1111000000.0,-938000000.0,NaN
Change In Working Capital,-903000000.0,-1316000000.0,335000000.0,-3199000000.0,NaN
Change In Other Working Capital,-1523000000.0,-1531000000.0,-442000000.0,-250000000.0,NaN
Change In Other Current Liabilities,NaN,NaN,NaN,NaN,-989000000.0
Change In Payables And Accrued Expense,637000000.0,495000000.0,251000000.0,-222000000.0,NaN
Change In Accrued Expense,NaN,NaN,27000000.0,222000000.0,-91000000.0
Change In Payable,637000000.0,495000000.0,251000000.0,-222000000.0,NaN
Change In Account Payable,637000000.0,495000000.0,251000000.0,-222000000.0,NaN
Change In Inventory,-214000000.0,45000000.0,-503000000.0,-183000000.0,NaN
Change In Receivables,197000000.0,-325000000.0,1029000000.0,-2544000000.0,NaN
Changes In Account Receivables,197000000.0,-325000000.0,1029000000.0,-2544000000.0,NaN
Other Non Cash Items,294000000.0,-3174000000.0,-4707000000.0,2340000000.0,NaN
Provisionand Write Offof Assets,614000000.0,472000000.0,1926000000.0,4747000000.0,NaN
Asset Impairment Charge,266000000.0,-773000000.0,426000000.0,1308000000.0,NaN
Depreciation Amortization Depletion,3070000000.0,3171000000.0,3034000000.0,3215000000.0,NaN
Operating Gains Losses,1539000000.0,-924000000.0,936000000.0,2650000000.0,NaN
Earnings Losses From Equity Investments,1108000000.0,-305000000.0,1271000000.0,1020000000.0,NaN
Gain Loss On Investment Securities,-1212000000.0,-1594000000.0,-203000000.0,1081000000.0,NaN
Net Foreign Currency Exchange Gain Loss,1643000000.0,975000000.0,-132000000.0,549000000.0,NaN
Net Income From Continuing Operations,11151000000.0,19781000000.0,29541000000.0,6990000000.0,NaN

In [31]:
stock.quarterly_cash_flow

,2024-03-31,2023-12-31,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30
Free Cash Flow,2181000000.0,2671000000.0,1402000000.0,692000000.0,2480000000.0,NaN,NaN
Repurchase Of Capital Stock,-275000000.0,-44000000.0,-546000000.0,-1361000000.0,-763000000.0,NaN,NaN
Repayment Of Debt,-103000000.0,-119000000.0,-60000000.0,-626000000.0,-86000000.0,NaN,NaN
Issuance Of Debt,870000000.0,0.0,150000000.0,1500000000.0,300000000.0,NaN,NaN
Capital Expenditure,-1395000000.0,-2118000000.0,-1464000000.0,-1208000000.0,-1130000000.0,NaN,NaN
End Cash Position,3790000000.0,3609000000.0,3967000000.0,4983000000.0,4705000000.0,NaN,NaN
Other Cash Adjustment Outside Changein Cash,NaN,-703000000.0,0.0,0.0,0.0,0.0,NaN
Beginning Cash Position,3609000000.0,3967000000.0,4983000000.0,4705000000.0,4736000000.0,NaN,NaN
Effect Of Exchange Rate Changes,-40000000.0,19000000.0,-49000000.0,67000000.0,32000000.0,NaN,NaN
Changes In Cash,221000000.0,326000000.0,-967000000.0,211000000.0,-63000000.0,NaN,NaN
Financing Cash Flow,-1836000000.0,-2236000000.0,-2134000000.0,-622000000.0,-2347000000.0,NaN,NaN
Cash From Discontinued Financing Activities,NaN,0.0,0.0,0.0,0.0,0.0,NaN
Cash Flow From Continuing Financing Activities,-1836000000.0,-2236000000.0,-2134000000.0,-622000000.0,-2347000000.0,NaN,NaN
Net Other Financing Charges,NaN,-33000000.0,NaN,-135000000.0,-3000000.0,-2000000.0,-3000000.0
Cash Dividends Paid,-2328000000.0,-2040000000.0,-1678000000.0,0.0,-1795000000.0,NaN,NaN
Net Common Stock Issuance,-275000000.0,-44000000.0,-546000000.0,-1361000000.0,-763000000.0,NaN,NaN
Common Stock Payments,-275000000.0,-44000000.0,-546000000.0,-1361000000.0,-763000000.0,NaN,NaN
Net Issuance Payments Of Debt,767000000.0,-119000000.0,90000000.0,874000000.0,214000000.0,NaN,NaN
Net Long Term Debt Issuance,767000000.0,-119000000.0,90000000.0,874000000.0,214000000.0,NaN,NaN
Long Term Debt Payments,-103000000.0,-119000000.0,-60000000.0,-626000000.0,-86000000.0,NaN,NaN
Long Term Debt Issuance,870000000.0,0.0,150000000.0,1500000000.0,300000000.0,NaN,NaN
Investing Cash Flow,-1519000000.0,-2227000000.0,-1699000000.0,-1067000000.0,-1326000000.0,NaN,NaN
Cash From Discontinued Investing Activities,NaN,0.0,0.0,0.0,0.0,0.0,NaN
Cash Flow From Continuing Investing Activities,-1519000000.0,-2227000000.0,-1699000000.0,-1067000000.0,-1326000000.0,NaN,NaN
Net Other Investing Changes,-83000000.0,309000000.0,-235000000.0,-30000000.0,-67000000.0,NaN,NaN
Dividends Received Cfi,3000000.0,99000000.0,0.0,105000000.0,0.0,NaN,NaN
Net Investment Purchase And Sale,-44000000.0,55000000.0,0.0,67000000.0,-55000000.0,NaN,NaN
Sale Of Investment,NaN,NaN,NaN,67000000.0,NaN,625000000.0,118000000.0
Purchase Of Investment,-44000000.0,NaN,NaN,NaN,-55000000.0,NaN,-70000000.0
Net Business Purchase And Sale,0.0,NaN,NaN,-1000000.0,-74000000.0,-577000000.0,140000000.0
Sale Of Business,NaN,NaN,NaN,0.0,NaN,NaN,140000000.0
Purchase Of Business,0.0,NaN,NaN,-1000000.0,-74000000.0,0.0,0.0
Net PPE Purchase And Sale,NaN,NaN,NaN,NaN,NaN,NaN,140000000.0
Sale Of PPE,NaN,NaN,NaN,NaN,NaN,NaN,140000000.0
Capital Expenditure Reported,-1395000000.0,-2118000000.0,-1464000000.0,-1208000000.0,-1130000000.0,NaN,NaN
Operating Cash Flow,3576000000.0,4789000000.0,2866000000.0,1900000000.0,3610000000.0,NaN,NaN
Cash From Discontinued Operating Activities,NaN,0.0,0.0,0.0,0.0,0.0,NaN
Cash Flow From Continuing Operating Activities,3576000000.0,4789000000.0,2866000000.0,1900000000.0,3610000000.0,NaN,NaN
Taxes Refund Paid,-506000000.0,-259000000.0,-720000000.0,-574000000.0,-337000000.0,NaN,NaN
Interest Paid Cfo,-186000000.0,-306000000.0,-174000000.0,-327000000.0,-169000000.0,NaN,NaN
Change In Working Capital,1378000000.0,-858000000.0,-186000000.0,-598000000.0,739000000.0,NaN,NaN
Change In Other Working Capital,-309000000.0,-121000000.0,-159000000.0,-764000000.0,-479000000.0,NaN,NaN
Change In Payables And Accrued Expense,378000000.0,-308000000.0,480000000.0,570000000.0,-105000000.0,NaN,NaN
Change In Accrued Expense,NaN,NaN,NaN,NaN,NaN,NaN,158000000.0
Change In Payable,378000000.0,-308000000.0,480000000.0,570000000.0,-105000000.0,NaN,NaN
Change In Account Payable,378000000.0,-308000000.0,480000000.0,570000000.0,-105000000.0,NaN,NaN
Change In Inventory,-626000000.0,403000000.0,-97000000.0,-157000000.0,-363000000.0,NaN,NaN
Change In Receivables,1935000000.0,-832000000.0,-410000000.0,-247000000.0,1686000000.0,NaN,NaN
Changes In Account Receivables,1935000000.0,-832000000.0,-410000000.0,-247000000.0,1686000000.0,NaN,NaN
Other Non Cash Items,-131000000.0,591000000.0,-61000000.0,-406000000.0,170000000.0,NaN,NaN
Provisionand Write Offof Assets,NaN,290000000.0,184000000.0,140000000.0,0.0,133000000.0,NaN
Asset Impairment Charge,6000000.0,121000000.0,75000000.0,66000000.0,4000000.0,NaN,NaN
Depreciation Amortization Depletion,714000000.0,855000000.0,780000000.0,779000000.0,656000000.0,NaN,NaN
Operating Gains Losses,166000000.0,1204000000.0,-16000000.0,100000000.0,251000000.0,NaN,NaN
Earnings Losses From Equity Investments,-124000000.0,1152000000.0,-94000000.0,-5000000.0,55000000.0,NaN,NaN
Gain Loss On Investment Securities,-83000000.0,-263000000.0,-24000000.0,-645000000.0,-280000000.0,NaN,NaN
Net Foreign Currency Exchange Gain Loss,373000000.0,315000000.0,102000000.0,750000000.0,476000000.0,NaN,NaN
Net Income From Continuing Operations,2135000000.0,3151000000.0,2984000000.0,2720000000.0,2296000000.0,NaN,NaN

# Investidores

In [36]:
stock.major_holders

/home/gabriel/Projects/3A-ai/.venv/lib/python3.11/site-packages/yfinance/scrapers/holders.py:39: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  def institutional(self) -> pd.DataFrame:

  Breakdown                             Unnamed: 1
0    11.47%        % of Shares Held by All Insider
1    44.09%       % of Shares Held by Institutions
2    49.80%        % of Float Held by Institutions
3       554  Number of Institutions Holding Shares

In [37]:
stock.institutional_holders

/home/gabriel/Projects/3A-ai/.venv/lib/python3.11/site-packages/yfinance/scrapers/holders.py:39: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  def institutional(self) -> pd.DataFrame:

In [38]:
stock.mutualfund_holders

/home/gabriel/Projects/3A-ai/.venv/lib/python3.11/site-packages/yfinance/scrapers/holders.py:39: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  def institutional(self) -> pd.DataFrame:

# Ganho por ação (EPS)

Mostra datas de ganhos futuros e históricos, retornos no máximo nos próximos 4 trimestres e nos últimos 8 trimestres por padrão.

In [40]:
stock.earnings_dates

/home/gabriel/Projects/3A-ai/.venv/lib/python3.11/site-packages/yfinance/base.py:2093: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2025-04-25 11:00:00-03:00           NaN           NaN          NaN
2025-04-22 16:00:00-03:00           NaN           NaN          NaN
2025-02-20 16:00:00-03:00           NaN           NaN          NaN
2024-10-24 16:00:00-03:00           NaN           NaN          NaN
2024-07-25 16:00:00-03:00          3.25           NaN          NaN
2024-04-26 11:00:00-03:00          2.43          2.02      -0.1687
2024-04-26 11:00:00-03:00          2.43          2.02      -0.1687
2024-04-24 21:00:00-03:00          0.47          0.39      -0.1702
2024-03-08 07:00:00-03:00          4.64          2.84      -0.3879
2024-02-23 08:00:00-03:00          0.91          0.56      -0.3873
2024-02-22 16:00:00-03:00          4.64          2.84      -0.3879
2023-10-26 18:00:00-03:00          0.60          0.66       0.0982

# Notícias

In [42]:
stock.news

[{'uuid': '9fb209b3-5e62-3141-a252-91dc85ccd9c2',
  'title': "Investors Overreacted to Expedia's Earnings",
  'publisher': 'GuruFocus.com',
  'link': 'https://finance.yahoo.com/news/investors-overreacted-expedias-earnings-140003675.html',
  'providerPublishTime': 1717682403,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/PHbHU2LTRsHJ8k.NoPuL5g--~B/aD0yNzI7dz04NjY7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/us.finance.gurufocus/cd8de9fe6d7cf8404b7121e6e8fe78eb',
     'width': 866,
     'height': 272,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/2mxuPLJu1nn3pA_ec.bswQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/us.finance.gurufocus/cd8de9fe6d7cf8404b7121e6e8fe78eb',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['EXPE', 'GOOG']},
 {'uuid': 'c4acd21e-5418-3ab4-bd8a-86dfcef945ee',
  'title': 'Lucid Group: Bearish Signals in an Unsustainable Business',
  'publisher': 'GuruFocus.com',
  'link': 'https://finance.yahoo.com/news/lucid-group-bearish-signals-unsustainable-140002137.html',
  'providerPublishTime': 1717682402,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/f.FRZoxJ028w3pwAygLpYA--~B/aD02Mjg7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/us.finance.gurufocus/14a78611445d0ecbd96b107503235618',
     'width': 1200,
     'height': 628,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/LfS08al1axEDm5OmlVot1Q--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/us.finance.gurufocus/14a78611445d0ecbd96b107503235618',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]}},
 {'uuid': 'b3f00a50-846a-3e70-a8ab-943fca436d85',
  'title': 'New analysis reveals the potential of green hydrogen',
  'publisher': 'Energy Global',
  'link': 'https://finance.yahoo.com/m/b3f00a50-846a-3e70-a8ab-943fca436d85/new-analysis-reveals-the.html',
  'providerPublishTime': 1717682400,
  'type': 'STORY'},
 {'uuid': 'c31f92b5-8fd9-3e6b-9925-3e7a486b3517',
  'title': 'Novavax stock rises on COVID vaccine delivery projections',
  'publisher': 'Yahoo Finance Video',
  'link': 'https://finance.yahoo.com/video/novavax-stock-rises-covid-vaccine-135817034.html',
  'providerPublishTime': 1717682297,
  'type': 'VIDEO',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/MElSUpqXR9a_Ar9SKl5Mvg--~B/aD0yMjUxO3c9NDAwMDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2024-06/ae72eeb0-240c-11ef-bd97-a350ffe09e34',
     'width': 4000,
     'height': 2251,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/92zn56x_3QZklVuq2Agq3A--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://s.yimg.com/os/creatr-uploaded-images/2024-06/ae72eeb0-240c-11ef-bd97-a350ffe09e34',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['NVAX']},
 {'uuid': '7cde9b23-3d9a-3874-b785-8985980d78fb',
  'title': 'Q1 2025 Semtech Corp Earnings Call',
  'publisher': 'Thomson Reuters StreetEvents',
  'link': 'https://finance.yahoo.com/news/q1-2025-semtech-corp-earnings-135713939.html',
  'providerPublishTime': 1717682233,
  'type': 'STORY',
  'relatedTickers': ['SMTC']},
 {'uuid': 'e7a7991a-face-3882-b2f3-97688e6a5d81',
  'title': 'Beyond the Dumpling: Laoban Expands Product Offerings with Launch of Frozen Bao Buns',
  'publisher': 'PR Newswire',
  'link': 'https://finance.yahoo.com/news/beyond-dumpling-laoban-expands-product-135700894.html',
  'providerPublishTime': 1717682220,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/mgyYhdrgW6OotOUcW_dIuQ--~B/aD0xNjt3PTE2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/prnewswire.com/43074a829dce40ec9870e96d1432d391',
     'width': 16,
     'height': 16,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/F37VwDx2wHA.PEEzml0h4Q--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/prnewswire.com/43074a829dce40ec9870e96d1432d391',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]}},
 {'uuid': 'b3f600dd-d744-3560-9974-1a7c5900c73d',
  'title': 'New Product Safety Recalls',
  'publisher': 'PR Newswire',
  'link': 'https://finance.yahoo.com/news/product-safety-recalls-135500747.html',
  'providerPublishTime': 1717682100,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/HxUgcHEbZlsmkQisgeClow--~B/aD00MDA7dz0zMDk7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/prnewswire.com/5dffd37a4e76516f41c4ff9d131cc1c7',
     'width': 309,
     'height': 400,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/kmdX5iyIkoCf5UrNr_h6VQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/prnewswire.com/5dffd37a4e76516f41c4ff9d131cc1c7',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]}},
 {'uuid': 'c2c288fb-2ac0-3917-bf8e-b15c15e046c4',
  'title': 'Greystone Real Estate Capital Syndication Platform Now Live',
  'publisher': 'GlobeNewswire',
  'link': 'https://finance.yahoo.com/news/greystone-real-estate-capital-syndication-135500956.html',
  'providerPublishTime': 1717682100,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/0Yth1StOBjIzIy3BuayBoA--~B/aD00MDA7dz00MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/globenewswire.com/17451e9b746ac919a7a41a58bcf4dfa5',
     'width': 400,
     'height': 400,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/ATDuZ3rfVu9GheSXtdMEAw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/globenewswire.com/17451e9b746ac919a7a41a58bcf4dfa5',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]}}]

# Representação